- .travis.yml
- pyaptly/graph_test.py
- pyaptly/test_test.py
on travis.
* The dependency-graphs now have only 20 commands
* A command provides/requires max 10 commands
* The yaml merge test now has a max length of 10 per leave
* The yaml merge test now has a max of 30 leaves
* Allowing deeper testing on Travis (max examples=10000)
> Making hypothesis examples smaller to avoid timeouts

- pyaptly/__init__.py
The previous version would run through 3 levels of loops, each across all existing
snapshots. Thus, if we had ~1000 snapshots (real-world usage), this would cause a
billion iterations.
This patch now only iterates over the whole snapshot list exactly once.
This fixes #8
> Fix exponential complexity when reading snapshot map.

- pyaptly/test.py
In some configurations / distributions, GnuPG insists on having a socket
file in ~/.gnupg, which prevents the copying that directory (shutil.copytree
is not smart enough to detect sockets).
So, we remove the socket before the copy, if it exists.
> Explicitly remove gnupg socket file before copy.

- pyaptly/__init__.py
This fixes #18. When executing `snapshot update` pyaptly fails if it encounters a publish endpoint, which directly publishes repos without snapshots.
> Fix bug when executing snapshot update

- setup.py
I'd say the GitHub repo is more useful when a potential user is looking at the PyPI page and you already have your company URL in the author_email field.
> setup.py: Set url to GitHub repo

- pyaptly/__init__.py
- pyaptly/aptly_test.py
Snapshots can be referred to by name (string) or via dict,
which may contain a timestamp placeholder. This however is
not true in any case. Sometimes, dict-snapshots are just another
way of writing the name.
Therefore we cannot assume the "dict" form to contain a timestamp.
> Do not expect dict-snapshots to contain timestamps

- .requirements.txt
- .travis.yml
- Makefile
- Vagrantfile
- pyaptly/__init__.py
- pyaptly/dateround_test.py
- pyaptly/graph_test.py
- pyaptly/test.py
- pyaptly/test_test.py
pyaptly still runs under python 2.6 but this is not tested anymore.
As this is still an requirement added python 2.6 to travis again working around hypothesis tests which do not run under 2.6.
> Add python26 tests

- .gitignore
- doc/format.rst
- pyaptly/__init__.py
- pyaptly/publish.yml
Since aptly version 0.9.6 aptly per default also creates content files.
With large repositories this can take quiet some time but also cause memory allocation issues
see https://github.com/smira/aptly/issues/415
Therefore I added an additional option to pyaptly to be able to skip contents file for specific repos.
> Added additional option to skip contents file generation in publish

- .gitignore
- pyaptly/__init__.py
- pyaptly/aptly_test.py
This only works with aptly version >=0.9.8 (not released yet) as following change is needed:
https://github.com/smira/aptly/pull/472
> Use snapshot and publish show to build deps tree

- compose/Dockerfile
- compose/setup/config.toml
- compose/setup/setup
chore: update Dockerfile to use bitnami/minideb:bookworm as base image
> chore: add support for different architectures in docker build process

- pyaptly/mirror.py
> refactor: replace `check_call` with `run_command` (no-merge)

- pyaptly/conftest.py
- pyaptly/main.py
- pyaptly/state_reader.py
- pyaptly/tests/test_dateround.py
- pyaptly/tests/test_helpers.py
> chore: switch to toml (no merge)

- pyaptly/command.py
- pyaptly/conftest.py
- pyaptly/main.py
- pyaptly/mirror.py
- pyaptly/state_reader.py
- pyaptly/tests/test_dateround.py
- pyaptly/tests/test_helpers.py
- pyaptly/util.py
chore: fix typing of cmd_args
**do not merge**
> feat: import `CalledProcessError` for users of `run_command` (no merge, nl)

- tools/venv-rpm
although it seems technically correct that the package is noarch, I decided against forcing it. It seems like nothing is gained for the risk for corrupt __pycache__ files and similar things.
> fix: stop forcing noarch

- pyaptly/cli.py
- pyaptly/main.py
- pyaptly/mirror.py
- pyaptly/publish.py
- pyaptly/repo.py
- pyaptly/snapshot.py
- pyaptly/state_reader.py
- tools/rebuild-rpm
this is not much better, but the function name documents what is happening
> fix: get state_reader via function

- pyaptly/cli.py
- pyaptly/command.py
- pyaptly/conftest.py
- pyaptly/main.py
- pyaptly/mirror.py
- pyaptly/publish.py
- pyaptly/repo.py
- pyaptly/snapshot.py
- pyaptly/state_reader.py
- pyaptly/tests/test_graph.py
- pyaptly/tests/test_mirror.py
- pyaptly/tests/test_publish.py
- pyaptly/tests/test_snapshot.py
Removes the very time intensive `SystemStateReader.read()` function and use functions that directly return the variables.
Solve the caching Problem with `lru_cache`, which is cleared with `...clear_cache()` whenever a respective `Command` is run.
Since the `Command` already has a `provides` function with `known_dependency_types` which pretty much exactly resembles the state variables that should be cached, I wrote a small `Command.clear_caches()` function which clears caches whenever a Command has been run.
I added some `provides` definitions so that it *should* work consistently with the cache resetting.
I also split it up into various "easier to understand" feature-separate commits - they should even run through the tests individually :)
You can also read the commit notes to follow my …
> feat: Replace SystemStateReader.read() with lru_cache

- README.md
- docs/TUTORIAL.md
I thought writing some user docs is the best way to repeat what I just learned and analyzed :)
Some features are still ignored and `publish` is not even properly started, but we'll get there.
> docs: Add small how/why and user tutorial

- pyaptly/cli.py
- pyaptly/main.py
- pyaptly/tests/publish-publish.json
- pyaptly/tests/publish-publish.yaml
- pyaptly/tests/test_mirror.py
- pyaptly/tests/test_publish.py
- pyaptly/util.py
yaml has been deprecated, json has beed added to support automation
> feat: support toml, json and yaml

- .github/workflows/main.yml
- .github/workflows/pull-requests.yml
- Makefile
- poetry.lock
- pyaptly/__init__.py
- pyaptly/cli.py
- pyaptly/config_file.py
- pyaptly/tests/debug.toml
- pyaptly/tests/mirror-basic.toml
- pyaptly/tests/mirror-extra.toml
- pyaptly/tests/publish-current.toml
- pyaptly/tests/publish-previous.toml
- pyaptly/tests/publish-publish.toml
- pyaptly/tests/publish-repo.toml
- pyaptly/tests/publish.toml
- pyaptly/tests/repo.toml
- pyaptly/tests/snapshot-current.toml
- pyaptly/tests/snapshot-filter.toml
- pyaptly/tests/snapshot-merge.toml
- pyaptly/tests/snapshot-repo.toml
- pyaptly/tests/snapshot.toml
- pyaptly/tests/test_config_file.py
- pyaptly/tomli_w/__init__.py
- pyaptly/tomli_w/_writer.py
- pyproject.toml
the converter is still not perfect and optimized for pyaptly config files. we will add json as an option, too
reviewers: you can basically ignore the actual toml-generator. It is taken from upstream.
> fix: improve toml converter

- pyaptly/conftest.py
- pyaptly/main.py
- pyaptly/publish.py
- pyaptly/tests/publish-bad.toml
- pyaptly/tests/test_publish.py
There was just an ugly stack trace and pyaptly aborted. Now it just says that it wanted to archive a snapshot for a publish which wasn't there.
I also added a comment in preparation for an additional feature I'm planning to be able to run `pyaptly update CONFIG --create`. Also, something we ran into several times.
It currently requires a bash script that runs the proper `snapshot create; snapshot update; publish create; publish update` sequence which is a bit of an annoyance.
> fix: Don't fail if a to-be archived publish has missing snapshots

- poetry.lock
- pyproject.toml
- tools/rebuild-rpm
`types-jsonschema` is only a dev-dependency and `python3-jsonschema` needs to be added to the list of packages to be installed to create the rpm.
The version for `jsonschema` also needs to be lower, as rhel don't have version `4.23` packaged. Thus the requirement of `4.0` should be enough.
> Fix the rpm build, broken by bad configuration and missing package install

- pyaptly/mirror.py
Hi, this PR makes a follow up on the following issue : #123 
This brings basic flat repository support without disturbing too much the rest of the `aptly_cmd` construction : 
If the `components` field is missing from the [mirror] definition in the TOML file, we simply do not add the argument, that way we avoid the ghost argument that was creating the issue described.
Please let me me know if I could help furterer in the support of flat repositories!
> Basic support for flat repositories

- pyaptly/util.py
this is still not perfect, but will save some CPU cycles.
I recently copy-pasted from pyaptly and found an issue.
> fix: do not format log result if no log will be printed

- pyaptly/util.py
I recently copy-pasted from pyaptly and found an issue.
> fix: remove unused indenting of stdout/stderr
